import { readFile, readdir } from 'node:fs/promises'
import { resolve, relative } from 'node:path'
import { expect, it, vi } from 'vitest'
import { createBrowserBridge } from '$src/lib/native/browser-bridge'
import { loadBundledAuthoringContracts } from '$src/lib/contract/bundled-contracts'
import {
  loadBundledResourceResolution,
  loadBundledWorkflowPackageContract,
} from '$src/lib/package-contract/bundled-package-contract'
import type { GitPackageContext, GitPackageVersionRequest } from '$src/lib/git/types'
import { MARKETPLACE_INDEX_PATH } from '$src/lib/packages/marketplace-index'
import { createPackagePreparationBackend } from './package-preparation'

async function fixture() {
  const root = resolve('tests/fixtures/workflow-packages/laptop-diagnostic'),
    packageRoot = 'packages/laptop'
  const files: Record<string, string> = {}
  for (const entry of await readdir(root, { recursive: true, withFileTypes: true })) {
    if (!entry.isFile()) continue
    const absolute = entry.parentPath + '/' + entry.name
    files[packageRoot + '/' + relative(root, absolute).replaceAll('\\', '/')] = await readFile(absolute, 'utf8')
  }
  const native = createBrowserBridge({ initialFiles: files })
  const context: GitPackageContext = {
    workspaceId: 'browser-workspace',
    packageRoot,
    repository: { root: '/browser/workspace', branch: 'main', detachedHead: null },
    base: { kind: 'unborn', reference: 'refs/heads/main' },
    contextToken: 'context',
    committedManifestText: null,
    baselineManifestText: null,
    committedFiles: [],
    committedIndexText: null,
    workingIndexText: null,
    workingIndexHash: null,
  }
  native.gitReadPackageContext = vi.fn(async () => {
    try {
      const index = await native.workspaceReadTextArtifact(MARKETPLACE_INDEX_PATH)
      return { ...context, workingIndexText: index.text, workingIndexHash: index.sha256 }
    } catch (error) {
      if (error && typeof error === 'object' && 'code' in error && error.code === 'path_not_found') return context
      throw error
    }
  })
  native.gitPreviewPackageVersion = vi.fn(async (request: GitPackageVersionRequest) => ({
    authorizationToken: 'preview',
    packageRoot,
    base: context.base,
    version: request.version,
    message: request.message,
    changedPaths: [packageRoot + '/workflow-package.json', MARKETPLACE_INDEX_PATH],
    diff: '+ exact prepared package',
  }))
  native.gitCommitPackageVersion = vi.fn(async () => ({
    outcome: 'committed' as const,
    oid: 'commit',
    status: null,
    warnings: [],
  }))
  const backend = createPackagePreparationBackend({
    packageRoot,
    native,
    contract: await loadBundledWorkflowPackageContract(),
    resourceContract: (await loadBundledResourceResolution()).contract,
    authoring: await loadBundledAuthoringContracts(),
    flush: async () => {},
  })
  return { backend, native, context, files, packageRoot }
}
it('prepares exact generated bytes and obtains a fresh native preview without committing', async () => {
  const { backend, native, packageRoot } = await fixture()
  const apply = vi.spyOn(native, 'workspaceApplyTransaction')
  const review = await backend.validate()
  expect(review.analysis.ready).toBe(true)
  const preview = await backend.prepare(review.snapshot, { version: '1.0.1', message: 'Prepare laptop' })
  expect(preview).toMatchObject({ version: '1.0.1', message: 'Prepare laptop', diff: '+ exact prepared package' })
  expect((await native.workspaceReadTextArtifact(packageRoot + '/workflow-package.json')).text).toContain(
    '"version": "1.0.1"',
  )
  expect((await native.workspaceReadTextArtifact(packageRoot + '/digests.json')).text).toContain('packageDigest')
  expect((await native.workspaceReadTextArtifact(MARKETPLACE_INDEX_PATH)).text).toContain('1.0.1')
  expect(native.gitCommitPackageVersion).not.toHaveBeenCalled()
  expect(apply).toHaveBeenCalledWith(expect.objectContaining({ packageSnapshotToken: expect.any(String) }))
})
it('rejects changed source bytes before modifying the selected version', async () => {
  const { backend, native, files, packageRoot } = await fixture()
  const review = await backend.validate()
  const path = packageRoot + '/scripts/analyze-snapshot.py',
    read = await native.workspaceReadTextArtifact(path)
  await native.workspaceWriteTextArtifact({
    relativePath: path,
    text: read.text + '\n# Changed\n',
    expectedCurrentHash: read.sha256,
  })
  await expect(backend.prepare(review.snapshot, { version: '1.0.1', message: 'Prepare' })).rejects.toThrow(
    'package_source_changed',
  )
  expect((await native.workspaceReadTextArtifact(packageRoot + '/workflow-package.json')).text).toBe(
    files[packageRoot + '/workflow-package.json'],
  )
  expect(native.gitPreviewPackageVersion).not.toHaveBeenCalled()
})
it('rejects new unreviewed package membership before writing', async () => {
  const { backend, native, packageRoot } = await fixture()
  const review = await backend.validate()
  await native.workspaceWriteTextArtifact({
    relativePath: packageRoot + '/unreviewed.txt',
    text: 'new',
    expectedCurrentHash: null,
  })
  await expect(backend.prepare(review.snapshot, { version: '1.0.1', message: 'Prepare' })).rejects.toThrow(
    'package_source_changed',
  )
  expect(native.gitPreviewPackageVersion).not.toHaveBeenCalled()
})
it('retains generated files on a Git preview failure and never claims a commit', async () => {
  const { backend, native, packageRoot } = await fixture()
  const review = await backend.validate()
  vi.mocked(native.gitPreviewPackageVersion).mockRejectedValue(new Error('git_identity_missing'))
  await expect(backend.prepare(review.snapshot, { version: '1.0.1', message: 'Prepare' })).rejects.toThrow(
    'git_identity_missing',
  )
  expect((await native.workspaceReadTextArtifact(packageRoot + '/digests.json')).text).toContain('packageDigest')
  expect(native.gitCommitPackageVersion).not.toHaveBeenCalled()
})

it('allows a new explicit preview after changing the chosen version without accepting unrelated edits', async () => {
  const { backend, native, context, packageRoot } = await fixture()
  vi.mocked(native.gitReadPackageContext).mockImplementation(async () => {
    try {
      const index = await native.workspaceReadTextArtifact(MARKETPLACE_INDEX_PATH)
      return { ...context, workingIndexText: index.text, workingIndexHash: index.sha256 }
    } catch {
      return context
    }
  })
  const review = await backend.validate()
  await backend.prepare(review.snapshot, { version: '1.0.1', message: 'First preview' })
  await expect(
    backend.prepare(review.snapshot, { version: '1.0.2', message: 'Second preview' }),
  ).resolves.toMatchObject({ version: '1.0.2', message: 'Second preview' })
  const path = packageRoot + '/new-unreviewed.txt'
  await native.workspaceWriteTextArtifact({ relativePath: path, text: 'new', expectedCurrentHash: null })
  await expect(backend.prepare(review.snapshot, { version: '1.0.3', message: 'Changed again' })).rejects.toThrow(
    'package_source_changed',
  )
  expect(native.gitCommitPackageVersion).not.toHaveBeenCalled()
})

it.each([false, true])(
  'preserves recovery from both successful mutations when later preview fails: %s',
  async (fails) => {
    const { backend, native } = await fixture()
    const retained = (path: string) => ({
      relativePath: path,
      destinationPath: 'C:/Studio/recovery/' + path.split('/').at(-1),
      status: 'recoveryRetained' as const,
      message: 'Manual recovery copy retained.',
    })
    const manifestReceipt = retained('packages/laptop/workflow-package.json'),
      generatedReceipt = retained('packages/laptop/digests.json')
    const apply = native.workspaceApplyTransaction.bind(native),
      generated = native.workspaceReplaceGeneratedFiles.bind(native)
    native.workspaceApplyTransaction = async (request) => {
      const result = await apply(request)
      return { ...result, results: [...result.results, manifestReceipt] }
    }
    native.workspaceReplaceGeneratedFiles = async (request) => {
      const result = await generated(request)
      return { ...result, results: [...result.results, generatedReceipt] }
    }
    const review = await backend.validate()
    if (fails) vi.mocked(native.gitPreviewPackageVersion).mockRejectedValue(new Error('git_identity_missing'))
    const result = backend.prepare(review.snapshot, { version: '1.0.1', message: 'Prepare laptop' })
    if (fails)
      await expect(result).rejects.toMatchObject({
        message: 'git_identity_missing',
        pathResults: [manifestReceipt, generatedReceipt],
      })
    else
      await expect(result).resolves.toMatchObject({
        recovery: { pathResults: [manifestReceipt, generatedReceipt], omittedPathResults: 0 },
      })
  },
)
